### ISSUE TITLE
Sort file list by reverse order

### ISSUE THREAD

**Issue by angeloalberico** [CelliesProjects/html5_audioplayer#4] opened 2023-10-27 15:51 UTC
Great script, super useful for my needs.  One tweak would make it near perfect for me.

Would it be possible to adjust how the list of mp3's are sorted?

I'd like to be able to sort by date modified but even reverse order of what it's currently doing (by file name) would work.

My use case is: I have mp3s that are automatically generated (named by 24 hour time) and dropped into a folder and I'd like to see the most recently added at the top of the list not the bottom.

I've looked through the code but I'm not super PHP savvy but I couldn't figure out how to adjust the sort the list of files.

Thanks

**Comment by CelliesProjects** [comment] 2023-10-28 10:25
Hi @angeloalberico I am also no php guru.

Just looked at the code and I think there is no easy way. 

I might look into this issue when time permits.

**Comment by angeloalberico** [comment] 2023-10-28 16:52
Hi @CelliesProjects
Thanks for the response.  

I spent a bit of time trying to figure it out, I believe the issue is how the list of folders or files are being built/displayed.  

Currently, it appears to  being done as a while loop and it just spits out each file/folder it encounters.  This way, there's no way to sort because there's no real list to sort.  We're at the the mercy of the default order which it's reading the file/folder.  Luckily it's at least reading by name/ascending by default.

My thoughts are, if the while loop first just built an array of files/folders then the array could be sorted and then it could be presented as desired sort (date or name, ascending or descending as you'd like).  However, doing this would require quite a bit of reworking of the current logic.

It's been years since I wrote PHP so I'm beyond rusty.  Time permitting, I may try to re-work the logic a bit.  If I have any luck I'll post here.

Still, it's a handy little app you made.

Cheers

**Comment by CelliesProjects** [comment] 2023-10-31 15:14
@angeloalberico I just read up on the issue and found a possible quick fix at [stackoverflow](https://stackoverflow.com/questions/7708387/glob-sort-by-name/7708393#7708393) that would be easy to try.

Change line 28 in `index.php` from

```php
foreach(glob($path.$validFiles,GLOB_BRACE)as$filename){
```

to

```php
foreach(array_reverse(glob($path.$validFiles,GLOB_BRACE)as$filename)){
```

This should only reverse the file ordering and not the folder ordering.
I did not test this.

My guess is that another array is created, so it might be a real memory hog to do it like this with folders that contain a lot of files.

**Comment by angeloalberico** [comment] 2023-11-01 22:31
Doing this produces:
*Parse error*: syntax error, unexpected token "as", expecting ")" in
*C:\web_root\index.php* on line *28*

**Comment by CelliesProjects** [comment] 2023-11-02 12:54
@angeloalberico I made a small typo.

It should be 

```php
foreach(array_reverse(glob($path.$validFiles,GLOB_BRACE))as$filename){
```

The issue is the closing `)` that should be after `GLOB_BRACE` and not after `$filename`

This time tested and working.

![reverseList](https://github.com/CelliesProjects/html5_audioplayer/assets/24290108/bb573114-1b5c-42b8-b32e-2f0bfdb01138)

**Comment by angeloalberico** [comment] 2023-11-02 15:18
That did it!  Thanks for your time and help!

**Comment by CelliesProjects** [comment] 2023-11-03 08:08
Closing this as solved.

**Closed as completed by CelliesProjects** 2023-11-03 08:08 UTC
